# Generated by Django 5.2.8 on 2025-11-26 17:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('e_area_restrita', models.BooleanField(default=False, help_text='Indica se o local armazena produtos de alto risco', verbose_name='É Área Restrita')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_estoque', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Local de Estoque',
                'verbose_name_plural': 'Locais de Estoque',
                'ordering': ['loja', 'nome'],
                'unique_together': {('loja', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='EstoqueAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantidade')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='estoque.localestoque', verbose_name='Local de Estoque')),
            ],
            options={
                'verbose_name': 'Estoque Atual',
                'verbose_name_plural': 'Estoques Atuais',
                'indexes': [models.Index(fields=['produto', 'local_estoque'], name='estoque_est_produto_ff1f24_idx'), models.Index(fields=['local_estoque', 'produto'], name='estoque_est_local_e_abc648_idx')],
                'unique_together': {('produto', 'local_estoque')},
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimento')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('referencia', models.CharField(blank=True, help_text='ID de pedido, nota, etc.', max_length=100, null=True, verbose_name='Referência')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('local_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_destino', to='estoque.localestoque', verbose_name='Local de Destino')),
                ('local_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_origem', to='estoque.localestoque', verbose_name='Local de Origem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-data_movimento'],
                'indexes': [models.Index(fields=['-data_movimento'], name='estoque_mov_data_mo_16bc05_idx'), models.Index(fields=['produto', '-data_movimento'], name='estoque_mov_produto_e0e324_idx'), models.Index(fields=['tipo_movimento', '-data_movimento'], name='estoque_mov_tipo_mo_213299_idx')],
            },
        ),
    ]
