# Generated by Django 5.0.6 on 2026-04-08 01:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_empresa'),
        ('estoque', '0001_initial'),
        ('produtos', '0010_catalogo_global_fase2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Custo unitário no momento da movimentação (obrigatório em entradas com valoração)', max_digits=10, null=True, verbose_name='Custo Unitário'),
        ),
        migrations.CreateModel(
            name='EstoqueValorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('custo_medio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo Médio')),
                ('quantidade_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Soma das quantidades em todos os locais desta empresa', max_digits=10, verbose_name='Quantidade Total em Estoque')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_valorados', to='core.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_valorados', to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Estoque Valorado',
                'verbose_name_plural': 'Estoques Valorados',
                'indexes': [models.Index(fields=['empresa', 'produto'], name='estoque_est_empresa_2a1885_idx')],
                'unique_together': {('empresa', 'produto')},
            },
        ),
    ]
