# Generated by Django 5.2.8 on 2026-04-08 02:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_empresa'),
        ('estoque', '0002_estoque_valorado_custo_unitario'),
        ('produtos', '0010_catalogo_global_fase2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaInterempresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('custo_unitario', models.DecimalField(decimal_places=4, help_text='Custo usado para atualizar custo médio na empresa destino', max_digits=10, verbose_name='Custo Unitário')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='core.empresa', verbose_name='Empresa Destino')),
                ('empresa_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='core.empresa', verbose_name='Empresa Origem')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='estoque.localestoque', verbose_name='Local de Destino')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_saida', to='estoque.localestoque', verbose_name='Local de Origem')),
                ('movimento_entrada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_entrada', to='estoque.movimentoestoque', verbose_name='Movimento de Entrada')),
                ('movimento_saida', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_saida', to='estoque.movimentoestoque', verbose_name='Movimento de Saída')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_interempresa', to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Transferência Interempresa',
                'verbose_name_plural': 'Transferências Interempresa',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa_origem', 'status'], name='estoque_tra_empresa_6fb7b7_idx'), models.Index(fields=['empresa_destino', 'status'], name='estoque_tra_empresa_9ec61e_idx'), models.Index(fields=['produto', '-created_at'], name='estoque_tra_produto_08ca39_idx')],
            },
        ),
    ]
