# Generated by Django 5.2.8 on 2025-11-26 18:49

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_evento', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('tipo_evento', models.CharField(choices=[('SAO_JOAO', 'São João'), ('REVEILLON', 'Réveillon'), ('CASAMENTO', 'Casamento'), ('CORPORATIVO', 'Corporativo'), ('RELIGIOSO', 'Religioso'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Evento')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('hora_evento', models.TimeField(blank=True, null=True, verbose_name='Hora do Evento')),
                ('endereco_logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('endereco_numero', models.CharField(max_length=20, verbose_name='Número')),
                ('endereco_complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('endereco_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('endereco_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('endereco_cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('estimativa_publico', models.IntegerField(blank=True, null=True, verbose_name='Estimativa de Público')),
                ('responsavel_evento', models.CharField(max_length=255, verbose_name='Responsável pelo Evento')),
                ('telefone_responsavel', core.fields.EncryptedCharField(max_length=20, verbose_name='Telefone do Responsável')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROPOSTA_ENVIADA', 'Proposta Enviada'), ('APROVADO', 'Aprovado'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='pessoas.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_venda', to='core.empresa', verbose_name='Empresa')),
                ('equipe_responsavel', models.ManyToManyField(blank=True, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Equipe Responsável')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='crm.lead', verbose_name='Lead')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_venda', to='core.loja', verbose_name='Loja')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Evento de Venda',
                'verbose_name_plural': 'Eventos de Venda',
                'ordering': ['-data_evento', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='eventos_eve_empresa_ba613b_idx'), models.Index(fields=['loja', 'data_evento'], name='eventos_eve_loja_id_b02203_idx'), models.Index(fields=['tipo_evento', 'data_evento'], name='eventos_eve_tipo_ev_f93252_idx'), models.Index(fields=['status', 'data_evento'], name='eventos_eve_status_fe2ed9_idx')],
            },
        ),
    ]
