# Generated by Django 5.2.8 on 2026-02-10 16:15

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventovenda',
            name='telefone_responsavel',
            field=core.fields.EncryptedCharField(max_length=255, verbose_name='Telefone do Responsável'),
        ),
    ]
