# Generated by Django 5.2.8 on 2025-11-26 17:26

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo de Pessoa')),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('apelido_nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apelido / Nome Fantasia')),
                ('cpf_cnpj', core.fields.EncryptedCharField(max_length=18, verbose_name='CPF / CNPJ')),
                ('rg_inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG / Inscrição Estadual')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', core.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('whatsapp', core.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa', verbose_name='Empresa')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_razao_social'],
                'indexes': [models.Index(fields=['empresa', 'is_active'], name='pessoas_cli_empresa_bb8fd2_idx'), models.Index(fields=['tipo_pessoa', 'is_active'], name='pessoas_cli_tipo_pe_a673fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', core.fields.EncryptedCharField(max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('telefone', core.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('whatsapp', core.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='core.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['empresa', 'is_active'], name='pessoas_for_empresa_cefe1e_idx')],
            },
        ),
    ]
