# Generated by Django 5.2.8 on 2026-02-10 16:08

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_encrypt_existing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=core.fields.EncryptedCharField(max_length=255, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
    ]
