# Generated by Django 5.2.8 on 2026-04-07 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_guia_inicial(apps, schema_editor):
    GuiaUso = apps.get_model('core', 'GuiaUso')
    GuiaUso.objects.get_or_create(
        slug='cadastro-empresa-loja-produtos',
        defaults={
            'titulo': 'Cadastro: Empresa, Loja e Produtos',
            'categoria': 'Operacao Inicial',
            'resumo': 'Passo a passo para iniciar os cadastros basicos do sistema.',
            'conteudo': (
                '1) Cadastre a Empresa em Administracao > Empresas.\n'
                '2) Cadastre a Loja em Administracao > Lojas.\n'
                '3) Configure dados fiscais da loja em Administracao > Config. Fiscal.\n'
                '4) Cadastre produtos em Cadastros > Produtos.\n\n'
                'Dica: use HOMOLOGACAO no inicio e valide o fluxo antes de PRODUCAO.'
            ),
            'ordem': 1,
            'publicado': True,
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_empresa_loja_cnpj_telefone_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('resumo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteudo (Markdown)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Guia de Uso',
                'verbose_name_plural': 'Guias de Uso',
                'ordering': ['ordem', 'titulo'],
                'indexes': [models.Index(fields=['publicado', 'is_active'], name='core_guia_pub_ativo_idx'), models.Index(fields=['categoria', 'ordem'], name='core_guia_cat_ordem_idx')],
            },
        ),
        migrations.RunPython(criar_guia_inicial, migrations.RunPython.noop),
    ]
