# Generated by Django 5.2.8 on 2026-04-07 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guiauso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20)),
                ('empresa_padrao', models.BooleanField(default=False, help_text='Se verdadeiro, esta empresa é sugerida na sessão quando o usuário ainda não escolheu outra.', verbose_name='Empresa Padrão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_acesso', to='core.empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso de Usuário à Empresa',
                'verbose_name_plural': 'Acessos de Usuários às Empresas',
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
