# Generated by Django 5.2.8 on 2025-11-26 17:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produto', to='core.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produto',
                'ordering': ['empresa', 'nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_interno', models.CharField(max_length=50, verbose_name='Código Interno')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('classe_risco', models.CharField(help_text='Ex: 1.4G, 1.3G', max_length=10, verbose_name='Classe de Risco')),
                ('subclasse_risco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Subclasse de Risco')),
                ('possui_restricao_exercito', models.BooleanField(default=False, verbose_name='Possui Restrição de Exército')),
                ('numero_certificado_exercito', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Certificado do Exército')),
                ('numero_lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Lote')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('condicoes_armazenamento', models.TextField(blank=True, null=True, verbose_name='Condições de Armazenamento')),
                ('ncm', models.CharField(max_length=10, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEST')),
                ('cfop_venda_dentro_uf', models.CharField(max_length=4, verbose_name='CFOP Venda Dentro UF')),
                ('cfop_venda_fora_uf', models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP Venda Fora UF')),
                ('unidade_comercial', models.CharField(default='UN', help_text='Ex: CX, PC, UN', max_length=10, verbose_name='Unidade Comercial')),
                ('origem', models.CharField(default='0', help_text='TODO: Trocar por choices', max_length=1, verbose_name='Origem')),
                ('csosn_cst', models.CharField(max_length=3, verbose_name='CSOSN / CST')),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Alíquota ICMS (%)')),
                ('preco_venda_sugerido', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Venda Sugerido')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoriaproduto', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.empresa', verbose_name='Empresa')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['empresa', 'codigo_interno'],
                'indexes': [models.Index(fields=['empresa', 'is_active'], name='produtos_pr_empresa_bb3338_idx'), models.Index(fields=['categoria', 'is_active'], name='produtos_pr_categor_c03660_idx'), models.Index(fields=['classe_risco', 'is_active'], name='produtos_pr_classe__9d56e6_idx'), models.Index(fields=['codigo_barras'], name='produtos_pr_codigo__f87624_idx')],
                'unique_together': {('empresa', 'codigo_interno')},
            },
        ),
    ]
