# Generated by Django 5.2.8 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_interno',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Código Interno'),
        ),
    ]
