# Generated by Django 5.2.8 on 2025-11-26 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_cofins',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.60'), help_text='Ex: 7,6%', max_digits=5, verbose_name='Alíquota COFINS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_icms_st',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de ICMS-ST se aplicável', max_digits=5, null=True, verbose_name='Alíquota ICMS-ST (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_ipi_compra',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Conforme NF do fornecedor', max_digits=5, null=True, verbose_name='Alíquota IPI Compra (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_ipi_venda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ex: 0% (geralmente zero na venda)', max_digits=5, verbose_name='Alíquota IPI Venda (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_pis',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.65'), help_text='Ex: 1,65%', max_digits=5, verbose_name='Alíquota PIS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cofins_cst',
            field=models.CharField(default='01', help_text='Ex: 01 (Operação Tributável com Alíquota Básica)', max_length=2, verbose_name='CST COFINS'),
        ),
        migrations.AddField(
            model_name='produto',
            name='icms_st_cst',
            field=models.CharField(blank=True, help_text='Ex: 10 (CST) ou 201 (CSOSN) - Somente se estado de destino exigir', max_length=3, null=True, verbose_name='CST/CSOSN ICMS-ST'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ipi_compra_cst',
            field=models.CharField(default='02', help_text='Ex: 02 (Entrada Tributada) - Conforme NF do fornecedor', max_length=2, verbose_name='CST IPI Compra'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ipi_venda_cst',
            field=models.CharField(default='52', help_text='Ex: 52 (Saída Tributada com Alíquota Zero)', max_length=2, verbose_name='CST IPI Venda'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pis_cst',
            field=models.CharField(default='01', help_text='Ex: 01 (Operação Tributável com Alíquota Básica)', max_length=2, verbose_name='CST PIS'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_icms',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Ex: 18% (BA)', max_digits=5, verbose_name='Alíquota ICMS (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, help_text='Ex: 09.001.00', max_length=10, null=True, verbose_name='CEST'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_venda_dentro_uf',
            field=models.CharField(help_text='Ex: 5.102 (venda dentro do estado)', max_length=4, verbose_name='CFOP Venda Dentro UF'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_venda_fora_uf',
            field=models.CharField(blank=True, help_text='Ex: 6.102 (venda fora do estado)', max_length=4, null=True, verbose_name='CFOP Venda Fora UF'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='csosn_cst',
            field=models.CharField(help_text='Ex: 102 (Simples) ou 00 (Regime Normal)', max_length=3, verbose_name='CSOSN / CST ICMS'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(help_text='Ex: 3604.10.00', max_length=10, verbose_name='NCM'),
        ),
    ]
