# Generated by Django 5.2.8 on 2025-11-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_aliquota_cofins_produto_aliquota_icms_st_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='classe_risco',
            field=models.CharField(choices=[('1.1G', '1.1G – Explosivo com risco de explosão em massa'), ('1.2G', '1.2G – Explosivo com risco de projeção'), ('1.3G', '1.3G – Explosivo com risco de fogo intenso/projeção'), ('1.4G', '1.4G – Explosivo com baixo risco (uso comum / varejo)'), ('1.4S', '1.4S – Explosivo com risco muito reduzido'), ('OUTRA', 'OUTRA / NÃO APLICÁVEL (para itens não-explosivos, acessórios, suportes, etc.)')], help_text='Classificação de risco do produto conforme normas de transporte e armazenamento', max_length=10, verbose_name='Classe de Risco'),
        ),
    ]
