# Generated by Django 5.2.8 on 2026-01-22 23:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_classe_risco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_cbs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.90'), help_text='Alíquota da CBS - Padrão 2026: 0,90% (fase de testes)', max_digits=5, verbose_name='Alíquota CBS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_ibs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Alíquota do IBS - Padrão 2026: 0,10% (fase de testes)', max_digits=5, verbose_name='Alíquota IBS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cclass_trib',
            field=models.CharField(blank=True, help_text='Código de Classificação Tributária (cClassTrib) conforme Reforma 2026', max_length=10, null=True, verbose_name='Classificação Tributária'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_cbs',
            field=models.CharField(blank=True, help_text='Código de Situação Tributária da CBS (Contribuição sobre Bens e Serviços)', max_length=3, null=True, verbose_name='CST-CBS'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_ibs',
            field=models.CharField(blank=True, help_text='Código de Situação Tributária do IBS (Imposto sobre Bens e Serviços)', max_length=3, null=True, verbose_name='CST-IBS'),
        ),
    ]
