# Generated by Django 5.2.8 on 2026-01-28 16:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_adicionar_campos_reforma_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoBarrasAlternativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_barras', models.CharField(db_index=True, help_text='EAN/GTIN alternativo mapeado para o produto principal', max_length=50, verbose_name='Código de Barras Alternativo')),
                ('descricao', models.CharField(blank=True, help_text='Ex: Embalagem promocional, Código fornecedor X, Caixa 12 un, etc.', max_length=100, verbose_name='Descrição/Motivo')),
                ('multiplicador', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Ex: Caixa com 12 unidades = 12.000', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Multiplicador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(help_text='Produto ao qual este código alternativo está vinculado', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_alternativos', to='produtos.produto', verbose_name='Produto Principal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Código de Barras Alternativo',
                'verbose_name_plural': 'Códigos de Barras Alternativos',
                'ordering': ['produto', 'codigo_barras'],
                'indexes': [models.Index(fields=['codigo_barras'], name='produtos_co_codigo__6f5758_idx'), models.Index(fields=['produto', 'is_active'], name='produtos_co_produto_649b06_idx')],
                'unique_together': {('produto', 'codigo_barras')},
            },
        ),
    ]
