# Generated by Django 5.2.8 on 2026-01-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('produtos', '0006_adicionar_codigo_barras_alternativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigobarrasalternativo',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Opcional. Fornecedor deste código alternativo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_alternativos', to='pessoas.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
