# Generated by Django 5.x

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guiauso'),
        ('produtos', '0007_adicionar_fornecedor_codigo_alternativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaCodigoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                (
                    'empresa',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sequencia_codigo_interno',
                        to='core.empresa',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Sequência Código Interno',
                'verbose_name_plural': 'Sequências Código Interno',
            },
        ),
    ]
