# Generated by Django 5.2.8 on 2026-01-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv_movel', '0001_criar_models_pdv_movel'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='atendente_tablet',
            field=models.ForeignKey(blank=True, help_text='Atendente que criou o pedido no tablet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_tablet', to='pdv_movel.atendentepdv', verbose_name='Atendente (Tablet)'),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='origem',
            field=models.CharField(choices=[('CAIXA', 'Caixa (PDV)'), ('TABLET', 'PDV Móvel (Tablet)'), ('ECOMMERCE', 'E-commerce'), ('WHATSAPP', 'WhatsApp')], default='CAIXA', help_text='Canal de origem do pedido', max_length=20, verbose_name='Origem do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='status',
            field=models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('ABERTO', 'Aberto'), ('FATURADO', 'Faturado'), ('CANCELADO', 'Cancelado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('ABANDONADO', 'Abandonado')], default='ORCAMENTO', max_length=20, verbose_name='Status'),
        ),
    ]
