# Generated by Django 5.2.8 on 2026-01-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_adicionar_campos_pdv_movel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='forma_pagamento_pretendida',
            field=models.CharField(blank=True, choices=[('NAO_INFORMADO', 'Não Informado'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_DEBITO', 'Cartão Débito'), ('CARTAO_CREDITO', 'Cartão Crédito'), ('PIX', 'PIX')], default='NAO_INFORMADO', help_text='Forma que o cliente pretende usar (informativa; pode ser alterada no caixa)', max_length=20, verbose_name='Forma de Pagamento Pretendida'),
        ),
    ]
