# Generated by Django 5.2.8 on 2026-01-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_forma_pagamento_pretendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='cpf_cnpj_nota',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ para incluir no documento fiscal', max_length=18, null=True, verbose_name='CPF/CNPJ na Nota'),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='data_emissao_cupom',
            field=models.DateTimeField(blank=True, help_text='Data/hora de emissão do documento fiscal', null=True, verbose_name='Data Emissão Cupom'),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='emitir_cupom_fiscal',
            field=models.BooleanField(default=False, help_text='Se deve emitir documento fiscal (SAT/NFC-e)', verbose_name='Emitir Cupom Fiscal'),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='numero_cupom_fiscal',
            field=models.CharField(blank=True, help_text='Número do cupom SAT ou chave NFC-e gerada', max_length=100, null=True, verbose_name='Número do Cupom Fiscal'),
        ),
    ]
