# Generated by GPT-5.2 on 2026-01-29

import decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def preencher_codigos_antigos(apps, schema_editor):
    """
    Preenche codigo_barras_usado para itens antigos (quando possível),
    usando o código principal do produto.

    - Não tenta inferir código alternativo.
    - Não cria placeholders quando produto não tem código principal.
    """
    ItemPedidoVenda = apps.get_model('vendas', 'ItemPedidoVenda')

    qs = (
        ItemPedidoVenda.objects.filter(codigo_barras_usado__isnull=True)
        .select_related('produto')
        .only('id', 'produto__codigo_barras')
    )

    # Itera sem salvar com full_clean (migração deve ser rápida e tolerante).
    for item in qs.iterator(chunk_size=2000):
        produto = getattr(item, 'produto', None)
        codigo = (getattr(produto, 'codigo_barras', None) or '').strip()
        if not codigo:
            continue
        ItemPedidoVenda.objects.filter(pk=item.pk).update(
            codigo_barras_usado=codigo,
            multiplicador_aplicado=decimal.Decimal('1.000'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_adicionar_fornecedor_codigo_alternativo'),
        ('vendas', '0004_campos_cupom_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidovenda',
            name='codigo_barras_usado',
            field=models.CharField(
                blank=True,
                help_text='Código escaneado/digitado na venda (principal ou alternativo).',
                max_length=50,
                null=True,
                verbose_name='Código de Barras Usado',
            ),
        ),
        migrations.AddField(
            model_name='itempedidovenda',
            name='codigo_alternativo_usado',
            field=models.ForeignKey(
                blank=True,
                help_text='Se foi usado um código alternativo, referência do cadastro.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vendas_registradas',
                to='produtos.codigobarrasalternativo',
                verbose_name='Código Alternativo Usado',
            ),
        ),
        migrations.AddField(
            model_name='itempedidovenda',
            name='multiplicador_aplicado',
            field=models.DecimalField(
                decimal_places=3,
                default=decimal.Decimal('1.000'),
                help_text='Snapshot do multiplicador no momento da venda (informativo/histórico).',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.001'))],
                verbose_name='Multiplicador Aplicado',
            ),
        ),
        migrations.AddIndex(
            model_name='itempedidovenda',
            index=models.Index(fields=['codigo_barras_usado'], name='item_codigo_usado_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedidovenda',
            index=models.Index(fields=['codigo_alternativo_usado'], name='item_codigo_alt_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedidovenda',
            index=models.Index(fields=['codigo_alternativo_usado', 'created_at'], name='item_alt_created_idx'),
        ),
        migrations.RunPython(preencher_codigos_antigos, migrations.RunPython.noop),
    ]

