# Generated by Django 5.2.8 on 2026-02-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_rastreio_codigos_alternativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidovenda',
            name='cpf_cnpj_nota',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ para incluir no documento fiscal', max_length=20, null=True, verbose_name='CPF/CNPJ na Nota'),
        ),
    ]
