# Generated by Django 5.2.8 on 2025-11-26 17:26

import core.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscalLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cnpj', core.fields.EncryptedCharField(max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('regime_tributario', models.CharField(help_text='Ex: SIMPLES_NACIONAL, LUCRO_PRESUMIDO, LUCRO_REAL', max_length=50, verbose_name='Regime Tributário')),
                ('certificado_arquivo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do Certificado')),
                ('senha_certificado', core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Senha do Certificado')),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], default='HOMOLOGACAO', max_length=20, verbose_name='Ambiente')),
                ('serie_nfe', models.CharField(default='001', max_length=3, verbose_name='Série NF-e')),
                ('serie_nfce', models.CharField(default='001', max_length=3, verbose_name='Série NFC-e')),
                ('proximo_numero_nfe', models.IntegerField(default=1, verbose_name='Próximo Número NF-e')),
                ('proximo_numero_nfce', models.IntegerField(default=1, verbose_name='Próximo Número NFC-e')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_fiscal', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração Fiscal da Loja',
                'verbose_name_plural': 'Configurações Fiscais das Lojas',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('serie', models.CharField(max_length=3, verbose_name='Série')),
                ('chave_acesso', models.CharField(max_length=44, verbose_name='Chave de Acesso')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('xml_arquivo', models.TextField(blank=True, null=True, verbose_name='XML da Nota')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='pessoas.fornecedor', verbose_name='Fornecedor')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_entrada', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
                'ordering': ['-data_entrada', '-numero'],
                'indexes': [models.Index(fields=['loja', '-data_entrada'], name='fiscal_nota_loja_id_a1cfbb_idx'), models.Index(fields=['fornecedor', '-data_entrada'], name='fiscal_nota_fornece_e2b74c_idx'), models.Index(fields=['chave_acesso'], name='fiscal_nota_chave_a_01d1a2_idx')],
                'unique_together': {('loja', 'chave_acesso')},
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_documento', models.CharField(choices=[('NFE', 'NF-e'), ('NFCE', 'NFC-e')], max_length=4, verbose_name='Tipo de Documento')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('serie', models.CharField(max_length=3, verbose_name='Série')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('xml_arquivo', models.TextField(blank=True, null=True, verbose_name='XML da Nota')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_PROCESSAMENTO', 'Em Processamento'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='pessoas.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_saida', to='core.loja', verbose_name='Loja')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Saída',
                'verbose_name_plural': 'Notas Fiscais de Saída',
                'ordering': ['-data_emissao', '-numero'],
                'indexes': [models.Index(fields=['loja', 'status'], name='fiscal_nota_loja_id_306d82_idx'), models.Index(fields=['cliente', '-data_emissao'], name='fiscal_nota_cliente_07ca9b_idx'), models.Index(fields=['chave_acesso'], name='fiscal_nota_chave_a_aa15a9_idx')],
                'unique_together': {('loja', 'tipo_documento', 'serie', 'numero')},
            },
        ),
    ]
