# Generated by Django 5.2.8 on 2026-01-22 23:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_notafiscalsaida_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='aliquota_cbs_padrao_2026',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.90'), help_text='Alíquota padrão da CBS quando produto não especificar (fase teste: 0,90%)', max_digits=5, verbose_name='Alíquota CBS Padrão 2026'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='aliquota_ibs_padrao_2026',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Alíquota padrão do IBS quando produto não especificar (fase teste: 0,10%)', max_digits=5, verbose_name='Alíquota IBS Padrão 2026'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='usar_reforma_2026',
            field=models.BooleanField(default=False, help_text='Ativa o cálculo de CBS e IBS conforme Reforma Tributária. Desligado = sistema funciona como antes. Ligado = inclui CBS/IBS nos cálculos e notas.', verbose_name='Ativar Reforma 2026'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='base_cbs_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Base CBS Total (Cache)'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='base_ibs_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor CONGELADO no momento da autorização - não recalcular', max_digits=15, null=True, verbose_name='Base IBS Total (Cache)'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='impostos_snapshot',
            field=models.JSONField(blank=True, help_text='JSON com impostos por item no momento da autorização (imutável)', null=True, verbose_name='Snapshot Impostos'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='valor_cbs_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor CBS Total (Cache)'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='valor_ibs_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor IBS Total (Cache)'),
        ),
    ]
