# Generated by Django 5.2.8 on 2026-02-10 16:15

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_nota_cache_impostos_reforma_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaofiscalloja',
            name='cnpj',
            field=core.fields.EncryptedCharField(max_length=255, verbose_name='CNPJ'),
        ),
    ]
