# Generated by Django 5.2.8 on 2026-04-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_historicoentradaestoque'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertanotafiscal',
            new_name='fiscal_aler_loja_id_423327_idx',
            old_name='fiscal_alert_loja_id_7a8f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='alertanotafiscal',
            new_name='fiscal_aler_chave_a_bb32c9_idx',
            old_name='fiscal_alert_chave_a_9b2c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='historicoentradaestoque',
            new_name='fiscal_hist_nota_fi_209aee_idx',
            old_name='fiscal_hist_nota_fi_idx',
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('ESTOQUE_PARCIAL', 'Estoque Parcial'), ('ESTOQUE_TOTAL', 'Estoque Total')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
    ]
