# Generated by Django 5.2.8 on 2025-11-26 17:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('CAIXA', 'Caixa'), ('CONTA_BANCARIA', 'Conta Bancária')], max_length=20, verbose_name='Tipo')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_financeiras', to='core.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data_movimento', models.DateField(verbose_name='Data do Movimento')),
                ('referencia', models.CharField(blank=True, help_text='ID de título, pedido, etc.', max_length=100, null=True, verbose_name='Referência')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.contafinanceira', verbose_name='Conta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Movimento Financeiro',
                'verbose_name_plural': 'Movimentos Financeiros',
                'ordering': ['-data_movimento'],
                'indexes': [models.Index(fields=['-data_movimento'], name='financeiro__data_mo_896f00_idx'), models.Index(fields=['conta', '-data_movimento'], name='financeiro__conta_i_4eeee4_idx'), models.Index(fields=['tipo', '-data_movimento'], name='financeiro__tipo_39b873_idx')],
            },
        ),
        migrations.CreateModel(
            name='TituloPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos_pagar', to='core.empresa', verbose_name='Empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_pagar', to='pessoas.fornecedor', verbose_name='Fornecedor')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_pagar', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Título a Pagar',
                'verbose_name_plural': 'Títulos a Pagar',
                'ordering': ['-data_vencimento'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='financeiro__empresa_398989_idx'), models.Index(fields=['fornecedor', '-data_vencimento'], name='financeiro__fornece_796cba_idx'), models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_0b71c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TituloReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_receber', to='pessoas.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos_receber', to='core.empresa', verbose_name='Empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_receber', to='core.loja', verbose_name='Loja')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_receber', to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Título a Receber',
                'verbose_name_plural': 'Títulos a Receber',
                'ordering': ['-data_vencimento'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='financeiro__empresa_471f08_idx'), models.Index(fields=['cliente', '-data_vencimento'], name='financeiro__cliente_46fe1d_idx'), models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_162dcf_idx')],
            },
        ),
    ]
