# Generated by Django 5.2.8 on 2026-01-21 00:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='categoria',
            field=models.CharField(default='OUTROS', help_text='Categoria do movimento (VENDA, RECEBIMENTO, PAGAMENTO, etc.)', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='titulo_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='financeiro.titulopagar', verbose_name='Título a Pagar'),
        ),
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='titulo_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='financeiro.tituloreceber', verbose_name='Título a Receber'),
        ),
        migrations.AddField(
            model_name='tituloreceber',
            name='conta_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos_receber', to='financeiro.contafinanceira', verbose_name='Conta Financeira'),
        ),
        migrations.AddField(
            model_name='tituloreceber',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='tituloreceber',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Desconto'),
        ),
        migrations.AddField(
            model_name='tituloreceber',
            name='valor_juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Juros'),
        ),
        migrations.AddField(
            model_name='tituloreceber',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Multa'),
        ),
        migrations.AddField(
            model_name='tituloreceber',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Recebido'),
        ),
    ]
