# Generated by Django 5.2.8 on 2025-12-20 01:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
        ('produtos', '0004_alter_produto_classe_risco'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompradorPirotecnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cpf', models.CharField(help_text='CPF formatado: 000.000.000-00', max_length=14, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('tipo_documento', models.CharField(choices=[('RG', 'RG - Registro Geral'), ('CNH', 'CNH - Carteira Nacional de Habilitação'), ('RNE', 'RNE - Registro Nacional de Estrangeiro'), ('PASSAPORTE', 'Passaporte'), ('OUTRO', 'Outro')], default='RG', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número do Documento')),
                ('orgao_emissor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor')),
                ('uf_emissor', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Emissor')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('aceite_termo', models.BooleanField(default=False, verbose_name='Aceite do Termo de Responsabilidade')),
                ('data_aceite', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Aceite')),
                ('ip_aceite', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Aceite')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Comprador de Produto Pirotécnico',
                'verbose_name_plural': 'Compradores de Produtos Pirotécnicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVendaPirotecnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('numero_certificado_exercito', models.CharField(blank=True, help_text='Número do certificado do produto vendido', max_length=50, null=True, verbose_name='Número do Certificado do Exército')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_venda', to='pdv.compradorpirotecnia', verbose_name='Comprador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('item_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_pirotecnia', to='vendas.itempedidovenda', verbose_name='Item do Pedido')),
                ('pedido_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pirotecnia', to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_venda_pirotecnia', to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Registro de Venda Pirotécnica',
                'verbose_name_plural': 'Registros de Vendas Pirotécnicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compradorpirotecnia',
            index=models.Index(fields=['cpf'], name='pdv_comprad_cpf_b8cc78_idx'),
        ),
        migrations.AddIndex(
            model_name='compradorpirotecnia',
            index=models.Index(fields=['data_nascimento'], name='pdv_comprad_data_na_7d65af_idx'),
        ),
        migrations.AddIndex(
            model_name='compradorpirotecnia',
            index=models.Index(fields=['-created_at'], name='pdv_comprad_created_3a0602_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovendapirotecnia',
            index=models.Index(fields=['pedido_venda'], name='pdv_registr_pedido__80c51a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovendapirotecnia',
            index=models.Index(fields=['comprador', '-created_at'], name='pdv_registr_comprad_ba85f4_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovendapirotecnia',
            index=models.Index(fields=['produto', '-created_at'], name='pdv_registr_produto_a15baf_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovendapirotecnia',
            index=models.Index(fields=['-created_at'], name='pdv_registr_created_d2b53e_idx'),
        ),
    ]
