# Generated by Django 5.2.8 on 2026-02-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_compradorpirotecnia_registrovendapirotecnia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradorpirotecnia',
            name='cpf',
            field=models.CharField(help_text='CPF formatado: 000.000.000-00', max_length=16, verbose_name='CPF'),
        ),
    ]
