# Generated by Django 5.2.8 on 2025-11-26 17:26

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', core.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('whatsapp', core.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('origem', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INDICACAO', 'Indicação'), ('EVENTO', 'Evento'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('aceita_comunicacoes', models.BooleanField(default=False, help_text='LGPD: Consentimento para receber comunicações de marketing', verbose_name='Aceita Comunicações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.empresa', verbose_name='Empresa')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('LIGACAO', 'Ligação'), ('PRESENCIAL', 'Presencial'), ('EMAIL', 'E-mail')], max_length=20, verbose_name='Canal')),
                ('descricao_resumida', models.CharField(max_length=255, verbose_name='Descrição Resumida')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_crm', to='pessoas.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Interação CRM',
                'verbose_name_plural': 'Interações CRM',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['empresa', 'status'], name='crm_lead_empresa_35aea1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['origem', 'status'], name='crm_lead_origem_dece3e_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaocrm',
            index=models.Index(fields=['-data_hora'], name='crm_interac_data_ho_9386d7_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaocrm',
            index=models.Index(fields=['lead', '-data_hora'], name='crm_interac_lead_id_81279f_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaocrm',
            index=models.Index(fields=['cliente', '-data_hora'], name='crm_interac_cliente_4f6e27_idx'),
        ),
    ]
