# Generated by Django 5.2.8 on 2026-02-10 16:15

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='telefone',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='whatsapp',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp'),
        ),
    ]
