# Generated by Django 5.2.8 on 2026-01-24 19:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_encrypt_existing_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPDVMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ativo', models.BooleanField(default=True, help_text='Ativa/desativa o PDV Móvel para esta loja', verbose_name='PDV Móvel Ativo')),
                ('timeout_pedido_minutos', models.IntegerField(default=30, help_text='Pedidos não pagos após este tempo aparecem como abandonados', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Timeout Pedido (minutos)')),
                ('permitir_edicao_pedido', models.BooleanField(default=True, help_text='Permite atendente editar pedido após salvar', verbose_name='Permitir Editar Pedido')),
                ('exigir_cliente', models.BooleanField(default=False, help_text='Obriga informar cliente ao criar pedido', verbose_name='Exigir Cliente')),
                ('permitir_desconto', models.BooleanField(default=False, help_text='Permite atendente dar desconto no tablet', verbose_name='Permitir Desconto')),
                ('desconto_maximo_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto máximo que atendente pode dar', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Desconto Máximo (%)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_pdv_movel', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração PDV Móvel',
                'verbose_name_plural': 'Configurações PDV Móvel',
            },
        ),
        migrations.CreateModel(
            name='AtendentePDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pin', models.CharField(help_text='PIN de 4 dígitos para login no tablet (ex: 1234)', max_length=4, verbose_name='PIN')),
                ('ativo', models.BooleanField(default=True, help_text='Atendente pode usar o tablet', verbose_name='Ativo')),
                ('ultima_sessao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sessão')),
                ('tablet_id', models.CharField(blank=True, help_text='Identificador do tablet usado (preenchido automaticamente)', max_length=100, verbose_name='ID do Tablet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendentes_pdv', to='core.loja', verbose_name='Loja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendente_pdv', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atendente PDV',
                'verbose_name_plural': 'Atendentes PDV',
                'unique_together': {('loja', 'pin')},
            },
        ),
    ]
