# Generated by Django 5.2.8 on 2025-11-26 23:25

import core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('produtos', '0004_alter_produto_classe_risco'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('telefone_contato', core.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('whatsapp_contato', core.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp de Contato')),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('origem', models.CharField(choices=[('BALCAO', 'Balcão'), ('EXTERNO', 'Externo'), ('EVENTO', 'Evento'), ('REVENDA', 'Revenda')], max_length=20, verbose_name='Origem')),
                ('tipo_operacao', models.CharField(choices=[('VAREJO', 'Varejo'), ('ATACADO', 'Atacado'), ('EVENTO_SHOW', 'Evento/Show'), ('REVENDER', 'Revender')], max_length=20, verbose_name='Tipo de Operação')),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('EXPIRADO', 'Expirado'), ('CONVERTIDO', 'Convertido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Bruto')),
                ('desconto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto Total')),
                ('acrescimo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Acréscimo Total')),
                ('total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Líquido')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='pessoas.cliente', verbose_name='Cliente')),
                ('condicao_pagamento_prevista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='vendas.condicaopagamento', verbose_name='Condição de Pagamento Prevista')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='core.empresa', verbose_name='Empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='core.loja', verbose_name='Loja')),
                ('pedido_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_origem', to='vendas.pedidovenda', verbose_name='Pedido Gerado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Orçamento de Venda',
                'verbose_name_plural': 'Orçamentos de Venda',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
                ('classe_risco', models.CharField(max_length=10, verbose_name='Classe de Risco')),
                ('subclasse_risco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Subclasse de Risco')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamentovenda', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Item do Orçamento de Venda',
                'verbose_name_plural': 'Itens dos Orçamentos de Venda',
                'ordering': ['orcamento', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamentovenda',
            index=models.Index(fields=['empresa', 'status'], name='orcamentos__empresa_5b6161_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentovenda',
            index=models.Index(fields=['loja', 'status'], name='orcamentos__loja_id_e5dcdb_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentovenda',
            index=models.Index(fields=['cliente', '-data_emissao'], name='orcamentos__cliente_4e640f_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentovenda',
            index=models.Index(fields=['vendedor', '-data_emissao'], name='orcamentos__vendedo_2f6c05_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentovenda',
            index=models.Index(fields=['origem', 'status'], name='orcamentos__origem_15b497_idx'),
        ),
    ]
