# Generated by Django 5.2.8 on 2026-02-10 16:15

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentovenda',
            name='telefone_contato',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Telefone de Contato'),
        ),
        migrations.AlterField(
            model_name='orcamentovenda',
            name='whatsapp_contato',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp de Contato'),
        ),
    ]
